Myenv/ECommerce/Accounts/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

Myenv/ECommerce/Cart/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('Cart/<int:pk>/',views.Cart_detail,
    ]

Myenv/ECommerce/ECommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView
from Cart import views
from Accounts import views as vie
from form import views as vi
from Accounts.views import signup
from form.views import feedback_form
from . import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Accounts/', include('Accounts.urls')),
    path('Accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'),name='home'),
    path('home/',views.item_list,name='item_list'),
	path('Checkout/',views.Checkout,name='Checkout'),
	path('Accounts/signup/',vie.SignUp,name='signup'),
	path('form/feedback_form/',vi.feedback_form,name='feedback_form'),
]
"""
urlpatterns+=staticfiles_urlpatterns()
"""
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Myenv/ECommerce/form/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
 
app_name = 'form'
urlpatterns = [
    path('feedback_form/', views.feedback_form, name='feedback_form'),
]

Myenv/ECommerce/Accounts/models.py
from django.db import models

# Create your models here.

Myenv/ECommerce/Cart/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

# Create your models here.

class item(models.Model):
    itemid=models.CharField(max_length=15)
    name=models.CharField(max_length=40)
    price=models.CharField(max_length=40)
    imglink=models.ImageField(upload_to='gallery')
    checked=models.BooleanField(default=False)

    def __str__(self):
        return self.name

Myenv/ECommerce/form/models.py
from django.db import models

# Create your models here.
class Feedback(models.Model):
	customer_name=models.CharField(max_length=20)
	email=models.EmailField()
	feedback=models.TextField()
	
	def __str__(self):
		return self.customer_name

Myenv/ECommerce/Cart/forms.py
from django import forms
from .models import item

class ItemForm(forms.ModelForm):
    class Meta:
        model=item
        fields=('itemid','name','price',)
        

Myenv/ECommerce/form/forms.py
from django import forms
from .models import Feedback

class FeedbackForm(forms.ModelForm):
	class Meta:
		model=Feedback
		fields=('customer_name','email','feedback')

Myenv/ECommerce/Accounts/views.py
from django.shortcuts import render

# Create your views here.

from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

def signup(request):
    return render(request,'signup.html',{})

Myenv/ECommerce/Cart/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import item

# Create your views here.

def item_list(request):
    items=item.objects.all()
    return render(request,'home.html',{'items':items})

def image(request):
    itemx=item()
    var=RequestContext(request,{'itemx':itemx})
    return render_to_response('home.html',var)
	
def Checkout(request):
    items=item.objects.all()
    return render(request,'Checkout.html',{'items':items})

Myenv/ECommerce/form/views.py
from django.shortcuts import render

# Create your views here.
from .forms import FeedbackForm

def feedback_form(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
 
        if form.is_valid():
            form.save()
            return render(request, 'form/thanks.html')
    else:
        form = FeedbackForm()
    return render(request, 'feedback_form.html', {'form': form})

Myenv/ECommerce/Accounts/templates/Accounts/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'CSS/Signup.css' %}">
<body>
<div id="Positioner">
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
</div>
</body>
{% endblock %}

Myenv/ECommerce/Cart/templates/Cart/item_list.html
{{items}}

Myenv/ECommerce/form/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}E-Cart{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

Myenv/ECommerce/form/templates/feedback_form.html
{% extends 'form/base.html' %}
 
{% block title %}Feedback Form{% endblock %}
 
{% block body %}
<form action="{% url 'feedback_form' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" />
</form>
{% endblock %}

Myenv/ECommerce/form/templates/form/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}E-Cart{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

Myenv/ECommerce/form/templates/form/feedback_form.html
{% extends 'form/base.html' %}
 
{% block title %}Feedback Form{% endblock %}
 
{% block body %}
<form action="{% url 'feedback_form' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" />
</form>
{% endblock %}

Myenv/ECommerce/form/templates/form/thanks.html
{% extends 'form/base.html' %}

{% block title %}Thanks{% endblock %}

{% block body %}
<h1>Thanks for your response.</h1>
<p><a href="{% url 'form:home' %}">Response again?</a></p>
{% endblock %}

Myenv/ECommerce/templates/Checkout.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}

	{% block content %}
	{% if user.is_authenticated %}
		{% for item in items %}
			{% if item.checked %}
				{{item.name}}
			{% endif %}
		{% endfor %}
	{% else %}
	  <p>You are not logged in</p>
	  <a href="{% url 'login' %}">login</a>
	{% endif %}
	{% endblock %}

Myenv/ECommerce/templates/home.html
{% extends 'base.html' %}
{% load static %}

<html>
	<head>
	{% block title %}Home{% endblock %}

	{% block content %}
	{% if user.is_authenticated %}
	<link rel="stylesheet" href="{% static 'CSS/goodies.css' %}">
	<script src="{% static 'JavaScript/Checkout.js' %}"></script>
	    <div class="container">
		{% for item in items %}
	<div class="Object">

    			<div class="img">

                	 <img class = "objimg" src="{{item.imglink.url}}" alt="Thanos_Gauntlet" width="200" height="200">
                </div>
				<div class="description">


        				<h2 >{{item.name}}</h2>
						<ul class="specs" >
	                		<li>Credits:4</li>
	                		<li>Special Edition</li>

                      <input id="{{item.itemid}}" class="buy_button" onclick="Adder({{item.price}},{{item.itemid}})" type="submit" value="ADD TO CART" name="{{item.itemid}}">
					  <button id="{{item.itemid}}" class="buy_button" onclick="Remove({{item.price}},{{item.itemid}},({{item.itemid}}-1000))" type="submit" value="">REMOVE FROM CART</button>

	                	</ul>
					</div>
			  <div class="price_n_offers">
              		<h3> &#8377 {{item.price}} </h3>
              		<p> <span class="strike_through_price"> &#8377 {{item.price}}</span> <span class="discount"> 33% off</span></p>
              		<p>Offers</p>
              		<ul class="offers">
              			<li>Credits can be redeemed</li>
              			<li>Special Price</li>
              		</ul>
              </div>
			 </div>
		{% endfor %}
		<input class="buy_button" onclick="Checkout()" type="submit" value="PROCEED TO CHECKOUT">

	  <p id="Top-Right"><a href="{% url 'logout' %}">logout</a></p>
	{% else %}
	<link rel="stylesheet" href="{% static 'CSS/Initial.css' %}">
	<body>
	  <p id="Status">You are not logged in</p>
	  <a id="Loginm" href="{% url 'login' %}">login</a>
	  <a id="signup" href="{% url 'signup' %}">Signup</a>
	  <!-- <a id="feedback" href="{% url 'feedback_form' %}">Feedback</a>-->
	  </body>
	{% endif %}
	{% endblock %}

Myenv/ECommerce/templates/item_list.html
{{items}}

Myenv/ECommerce/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'CSS/Signup.css' %}">
<body>
	<div id="Positioner">
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
  </div>
</body>
{% endblock %}